json.id                 schedule.id
json.user               schedule.user
json.plant              schedule.plant
json.last_watered_date  schedule.last_watered_date
json.time_changed       schedule.time_changed
json.growth_status      schedule.growth_status
json.status             schedule.status
json.created_at         schedule.created_at
json.updated_at         schedule.updated_at